### ISSUE TITLE
Tracking Issue for 0.1.0

### ISSUE THREAD

**Issue by zesterer** [veloren/game#68]
- [x] Basic world/chunk generation
    - [x] Client-side chunk generation
    - [x] Minor optimisation
- [x] Customizable key bindings
- [x] Single cube as player model
    - [x] We went a step further: basic player model
- [ ] Basic player movement
    - [x] X/Y movement
    - [x] Velocity
    - [x] Gravity
    - [ ] Jumping
    - [ ] Proper collision system
- [ ] Simple connected/disconnected server events, including entity updates
    - [x] Connection, disconnection
    - [x] Chat messages
    - [x] Realtime player / entity updates
- [ ] User interface
    - [ ] Chat interface
    - [ ] Ability to connect to server using UI
- [ ] Headless client
    - [x] Create headless client
    - [ ] Implement backspace in headless
- [ ] Repo Management
    - [ ] evaluate whats needed for gitlab (because if we do it now we have a short buffer to test it fully productive, to revert in case it doesnt fit before 0.2.0 start)
    - [ ] code style (evaluate all of them and check if anything needs to be done here)
    - [ ] remove old files no longer needed (.old files and worldtest?)
    - [ ] fix importing headers
    - [ ] rename classes
    - [ ] squash files together (e.g. in server) or make 2 files of one (e.g. client/lib) 
    - [ ] move files to correct folder
    - [ ] reduce warnings
    - [ ] remove unused dependencies
    - [ ] check if all dependencies share same version over project
    - [ ] write basic tests for smaller components
    - [ ] check comments
- [ ] have a public party at the server to cheer us up a little
